//! Shell cell — remote Glia REPL over Cap'n Proto.
//!
//! Evaluates Glia s-expressions in a persistent environment with
//! capability-scoped dispatch.  Registered via VatListener; each
//! incoming connection spawns a fresh cell with its own Env.
//!
//! This is the "nREPL for Wetware": client sends text, cell evaluates,
//! result comes back.  State persists across evals (def sticks).

use std::cell::RefCell;
use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::rc::Rc;

use capnp::capability::Promise;
use capnp_rpc::pry;

use glia::eval::{self, Dispatch, Env};
use glia::Val;

use wasip2::exports::cli::run::Guest;

// Shared effect handler factories.
use caps::{
    call_resume, eval_load, extract_method, get_graft_cap, make_host_handler, make_ipfs_handler,
    make_routing_handler, routing_capnp, system_capnp, stem_capnp, wrap_with_handlers,
};

// Shell-specific generated Cap'n Proto modules.
#[allow(dead_code)]
mod shell_capnp {
    include!(concat!(env!("OUT_DIR"), "/shell_capnp.rs"));
}
#[allow(dead_code)]
mod auction_capnp {
    include!(concat!(env!("OUT_DIR"), "/auction_capnp.rs"));
}

// Schema CID constants (generated by build.rs).
#[allow(dead_code)]
mod schema_ids {
    include!(concat!(env!("OUT_DIR"), "/schema_ids.rs"));
}

// Auction schema constants: COMPUTE_PROVIDER_SCHEMA (&[u8]) and COMPUTE_PROVIDER_CID (&str).
#[allow(dead_code)]
mod auction_schema_ids {
    include!(concat!(env!("OUT_DIR"), "/auction_schema_ids.rs"));
}

type Membrane = stem_capnp::membrane::Client;

// ---------------------------------------------------------------------------
// Session — capability context for the shell cell
// ---------------------------------------------------------------------------

struct ShellSession {
    host: Option<system_capnp::host::Client>,
    routing: Option<routing_capnp::routing::Client>,
    vat_client: Option<system_capnp::vat_client::Client>,
    initialized: bool,
}

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

type HandlerFn = for<'a> fn(
    &'a [Val],
    &'a RefCell<ShellSession>,
) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>>;

struct ShellDispatch<'s> {
    ctx: &'s RefCell<ShellSession>,
    table: &'s HashMap<&'static str, HandlerFn>,
}

impl<'s> Dispatch for ShellDispatch<'s> {
    fn call<'a>(
        &'a self,
        name: &'a str,
        args: &'a [Val],
    ) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>> {
        Box::pin(async move {
            match self.table.get(name) {
                Some(handler) => handler(args, self.ctx).await,
                None => Err(Val::from(format!("{name}: command not found"))),
            }
        })
    }
}

fn build_dispatch() -> HashMap<&'static str, HandlerFn> {
    let mut t: HashMap<&'static str, HandlerFn> = HashMap::new();
    t.insert("load", |a, _| Box::pin(std::future::ready(eval_load(a))));
    t.insert("help", |_, _| {
        Box::pin(std::future::ready(Ok(Val::Str(HELP_TEXT.to_string()))))
    });
    // Shell-specific exit: returns a sentinel keyword instead of process::exit.
    // The serve loop catches this and exits cleanly.
    t.insert("exit", |_, _| {
        Box::pin(std::future::ready(Ok(Val::Keyword("exit".into()))))
    });
    t
}

const HELP_TEXT: &str = "\
Remote Glia shell. Available commands:
  (perform host :id)       — peer identity
  (perform host :addrs)    — listen addresses
  (perform host :peers)    — connected peers
  (perform routing :find \"name\") — DHT lookup
  (perform auction :compare \"QmCid...\")       — compare fuel quotes
  (perform auction :compare \"QmCid...\" 5000000) — compare with custom fuel
  (help)                   — this message
  (exit)                   — disconnect";

// ---------------------------------------------------------------------------
// Auction: ProviderCollector — collects peer IDs from find_providers stream
// ---------------------------------------------------------------------------

struct ProviderCollector {
    providers: Rc<RefCell<Vec<Vec<u8>>>>,
    self_id: Vec<u8>,
    max: usize,
}

#[allow(refining_impl_trait)]
impl routing_capnp::provider_sink::Server for ProviderCollector {
    fn provider(
        self: Rc<Self>,
        params: routing_capnp::provider_sink::ProviderParams,
    ) -> Promise<(), capnp::Error> {
        let peer_id = match (|| -> Result<Vec<u8>, capnp::Error> {
            Ok(params.get()?.get_info()?.get_peer_id()?.to_vec())
        })() {
            Ok(id) => id,
            Err(e) => return Promise::err(e),
        };

        // Skip self.
        if peer_id == self.self_id {
            return Promise::ok(());
        }

        let mut providers = self.providers.borrow_mut();
        if providers.len() < self.max {
            providers.push(peer_id);
        }
        Promise::ok(())
    }

    fn done(
        self: Rc<Self>,
        _params: routing_capnp::provider_sink::DoneParams,
        _results: routing_capnp::provider_sink::DoneResults,
    ) -> Promise<(), capnp::Error> {
        Promise::ok(())
    }
}

// ---------------------------------------------------------------------------
// make_auction_handler — :compare effect handler for fuel quote comparison
// ---------------------------------------------------------------------------

fn make_auction_handler(
    routing: routing_capnp::routing::Client,
    vat_client: system_capnp::vat_client::Client,
    self_id: Vec<u8>,
) -> Val {
    Val::AsyncNativeFn {
        name: "auction-handler".into(),
        func: Rc::new(move |args: Vec<Val>| {
            let routing = routing.clone();
            let vat_client = vat_client.clone();
            let self_id = self_id.clone();
            Box::pin(async move {
                let (method, rest) = extract_method(&args[0])?;
                let resume = &args[1];

                match method.as_str() {
                    "compare" => {
                        // Parse args: wasm_cid (required), fuel (optional, default 1M).
                        let wasm_cid = match rest.first() {
                            Some(Val::Str(s)) => s.as_bytes().to_vec(),
                            Some(Val::Bytes(b)) => b.clone(),
                            _ => {
                                return Err(Val::from(
                                    "auction :compare — expected WASM CID string",
                                ))
                            }
                        };
                        let fuel: u64 = match rest.get(1) {
                            Some(Val::Int(n)) => *n as u64,
                            None => 1_000_000, // default 1M fuel
                            _ => {
                                return Err(Val::from(
                                    "auction :compare — fuel must be an integer",
                                ))
                            }
                        };

                        // 1. Discover providers via DHT.
                        let providers_buf = Rc::new(RefCell::new(Vec::<Vec<u8>>::new()));
                        let collector: routing_capnp::provider_sink::Client =
                            capnp_rpc::new_client(ProviderCollector {
                                providers: providers_buf.clone(),
                                self_id: self_id.clone(),
                                max: 10,
                            });

                        let mut fp_req = routing.find_providers_request();
                        {
                            let mut b = fp_req.get();
                            b.set_key(auction_schema_ids::COMPUTE_PROVIDER_CID);
                            b.set_count(20); // ask for extra, collector caps at 10
                            b.set_sink(collector);
                        }
                        fp_req
                            .send()
                            .promise
                            .await
                            .map_err(|e| Val::from(format!("auction: find_providers: {e}")))?;

                        let providers = providers_buf.borrow().clone();

                        if providers.is_empty() {
                            return call_resume(
                                resume,
                                Val::List(vec![Val::Str(
                                    "(no providers available)".to_string(),
                                )]),
                            );
                        }

                        // 2. Random sample if > 10 (collector already caps, but
                        //    defensive in case find_providers returns duplicates
                        //    that passed the filter).
                        let sampled = if providers.len() > 10 {
                            use rand::seq::SliceRandom;
                            let mut rng = rand::rng();
                            let mut shuffled = providers.clone();
                            shuffled.shuffle(&mut rng);
                            shuffled.truncate(10);
                            shuffled
                        } else {
                            providers
                        };

                        // 3. Dial each provider and request a quote.
                        //    Use a 5-second timeout per provider (via monotonic clock).
                        let now = std::time::SystemTime::now()
                            .duration_since(std::time::UNIX_EPOCH)
                            .unwrap_or_default()
                            .as_secs() as i64;

                        let mut quotes: Vec<(String, u64, u64, i64)> = Vec::new();

                        for peer_id in &sampled {
                            // Dial with timeout: 5 seconds.
                            let result = dial_and_quote(
                                &vat_client,
                                peer_id,
                                &wasm_cid,
                                fuel,
                            )
                            .await;

                            if let Ok((price, qfuel, expires)) = result {
                                // Filter expired quotes.
                                if expires > now {
                                    let encoded = bs58::encode(peer_id).into_string();
                                    quotes.push((encoded, price, qfuel, expires));
                                }
                            }
                            // Silently omit failures/timeouts.
                        }

                        if quotes.is_empty() && !sampled.is_empty() {
                            return call_resume(
                                resume,
                                Val::List(vec![Val::Str(
                                    "(all providers unreachable)".to_string(),
                                )]),
                            );
                        }

                        // 4. Sort by price ascending.
                        quotes.sort_by_key(|q| q.1);

                        // 5. Build result list of maps.
                        let result: Vec<Val> = quotes
                            .into_iter()
                            .map(|(provider, price, qfuel, expires)| {
                                Val::Map(vec![
                                    (
                                        Val::Keyword("provider".into()),
                                        Val::Str(provider),
                                    ),
                                    (
                                        Val::Keyword("price".into()),
                                        Val::Int(price as i64),
                                    ),
                                    (
                                        Val::Keyword("fuel".into()),
                                        Val::Int(qfuel as i64),
                                    ),
                                    (
                                        Val::Keyword("expires".into()),
                                        Val::Int(expires),
                                    ),
                                ])
                            })
                            .collect();

                        call_resume(resume, Val::List(result))
                    }
                    other => Err(Val::from(format!("auction: unknown method :{other}"))),
                }
            })
        }),
    }
}

/// Dial a ComputeProvider peer and request a quote.
///
/// Returns (price_per_m_fuel, fuel, expires_at) on success.
async fn dial_and_quote(
    vat_client: &system_capnp::vat_client::Client,
    peer_id: &[u8],
    wasm_cid: &[u8],
    fuel: u64,
) -> Result<(u64, u64, i64), capnp::Error> {
    // Dial the provider via VatClient.
    let mut dial_req = vat_client.dial_request();
    dial_req.get().set_peer(peer_id);
    dial_req
        .get()
        .set_schema(auction_schema_ids::COMPUTE_PROVIDER_SCHEMA);
    let dial_resp = dial_req.send().promise.await?;
    let provider: auction_capnp::compute_provider::Client =
        dial_resp.get()?.get_cap().get_as_capability()?;

    // Request a quote.
    let mut quote_req = provider.quote_request();
    quote_req.get().set_wasm_cid(wasm_cid);
    quote_req.get().set_fuel_requested(fuel);
    let quote_resp = quote_req.send().promise.await?;
    let q = quote_resp.get()?.get_quote()?;

    Ok((q.get_price_per_m_fuel(), q.get_fuel(), q.get_expires_at()))
}

// ---------------------------------------------------------------------------
// Shell server — Cap'n Proto interface implementation
// ---------------------------------------------------------------------------

struct ShellImpl {
    env: Rc<RefCell<Env>>,
    ctx: Rc<RefCell<ShellSession>>,
    dispatch: HashMap<&'static str, HandlerFn>,
    ready: Rc<std::cell::Cell<bool>>,
}

#[allow(refining_impl_trait)]
impl shell_capnp::shell::Server for ShellImpl {
    fn eval(
        self: capnp::capability::Rc<Self>,
        params: shell_capnp::shell::EvalParams,
        mut results: shell_capnp::shell::EvalResults,
    ) -> Promise<(), capnp::Error> {
        let text = match pry!(params.get()).get_text() {
            Ok(t) => match t.to_str() {
                Ok(s) => s.to_string(),
                Err(_) => {
                    results.get().set_result("invalid UTF-8 input");
                    results.get().set_is_error(true);
                    return Promise::ok(());
                }
            },
            Err(e) => {
                results.get().set_result(&format!("{e}"));
                results.get().set_is_error(true);
                return Promise::ok(());
            }
        };

        Promise::from_future(async move {
            // Check that the serve closure has finished initializing.
            if !self.ready.get() {
                results
                    .get()
                    .set_result("shell not ready (initialization in progress)");
                results.get().set_is_error(true);
                return Ok(());
            }

            if text.trim().is_empty() {
                results.get().set_result("");
                results.get().set_is_error(false);
                return Ok(());
            }

            // Parse
            let expr = match glia::read(&text) {
                Ok(expr) => expr,
                Err(e) => {
                    results.get().set_result(&format!("parse error: {e}"));
                    results.get().set_is_error(true);
                    return Ok(());
                }
            };

            // Wrap in effect handlers and evaluate
            let wrapped = wrap_with_handlers(&expr, &["auction"]);
            let dispatch = ShellDispatch {
                ctx: &*self.ctx,
                table: &self.dispatch,
            };
            match eval::eval_toplevel(&wrapped, &mut self.env.borrow_mut(), &dispatch).await {
                Ok(Val::Nil) => {
                    results.get().set_result("");
                    results.get().set_is_error(false);
                }
                Ok(Val::Keyword(ref k)) if k == "exit" => {
                    results.get().set_result("exit");
                    results.get().set_is_error(false);
                }
                Ok(result) => {
                    results.get().set_result(&format!("{result}"));
                    results.get().set_is_error(false);
                }
                Err(e) => {
                    results.get().set_result(&format!("{e}"));
                    results.get().set_is_error(true);
                }
            }
            Ok(())
        })
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

struct Shell;

impl Guest for Shell {
    fn run() -> Result<(), ()> {
        run_impl();
        Ok(())
    }
}

wasip2::cli::command::export!(Shell);

fn run_impl() {
    let env = Rc::new(RefCell::new(Env::new()));
    let ctx = Rc::new(RefCell::new(ShellSession {
        host: None,
        routing: None,
        vat_client: None,
        initialized: false,
    }));
    let ready = Rc::new(std::cell::Cell::new(false));

    let shell_impl = ShellImpl {
        env: Rc::clone(&env),
        ctx: Rc::clone(&ctx),
        dispatch: build_dispatch(),
        ready: Rc::clone(&ready),
    };
    let client: shell_capnp::shell::Client = capnp_rpc::new_client(shell_impl);

    system::serve(client.client, |membrane: Membrane| async move {
        // 1. Graft the membrane to obtain capabilities.
        let graft_resp = membrane.graft_request().send().promise.await?;
        let results = graft_resp.get()?;

        // Find capabilities by name in the graft caps list.
        let caps = results.get_caps()?;
        let host: system_capnp::host::Client = get_graft_cap(&caps, "host")?;
        let routing: routing_capnp::routing::Client = get_graft_cap(&caps, "routing")?;

        // Get network capabilities — vat_client for auction :compare handler.
        let network_resp = host.network_request().send().promise.await?;
        let network = network_resp.get()?;
        let vat_client = network.get_vat_client()?;

        // Resolve peer identity (needed by auction handler to skip self).
        let id_resp = host.id_request().send().promise.await?;
        let self_id = id_resp.get()?.get_peer_id()?.to_vec();

        // Populate session so cap handlers can access capabilities.
        {
            let mut s = ctx.borrow_mut();
            s.host = Some(host.clone());
            s.routing = Some(routing.clone());
            s.vat_client = Some(vat_client.clone());
            s.initialized = true;
        }

        // 2. Bind cap values + effect handlers into the environment.
        {
            let mut env = env.borrow_mut();
            let caps: [(&str, Val); 4] = [
                ("host", make_host_handler(host)),
                ("ipfs", make_ipfs_handler()),
                ("routing", make_routing_handler(routing.clone())),
                (
                    "auction",
                    make_auction_handler(routing, vat_client, self_id),
                ),
            ];
            for (name, handler) in caps {
                env.set(name.to_string(), Val::Nil);
                env.set(format!("{name}-handler"), handler);
            }
        }

        // 3. Load the prelude (macro definitions only, no capability calls).
        {
            let mut env = env.borrow_mut();
            let prelude_forms = glia::read_many(glia::PRELUDE).expect("prelude: parse error");
            struct NoopDispatch;
            impl Dispatch for NoopDispatch {
                fn call<'a>(
                    &'a self,
                    name: &'a str,
                    _args: &'a [Val],
                ) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>> {
                    Box::pin(std::future::ready(Err(Val::from(format!(
                        "{name}: not available"
                    )))))
                }
            }
            let noop = NoopDispatch;
            for form in &prelude_forms {
                let mut fut = Box::pin(eval::eval_toplevel(form, &mut env, &noop));
                let waker = std::task::Waker::noop();
                let mut cx = std::task::Context::from_waker(&waker);
                match fut.as_mut().poll(&mut cx) {
                    std::task::Poll::Ready(Ok(_)) => {}
                    std::task::Poll::Ready(Err(e)) => log::error!("prelude: {e}"),
                    std::task::Poll::Pending => log::error!("prelude: unexpected pending"),
                }
            }
        }

        ready.set(true);

        // Keep alive. The RPC system drives eval calls concurrently.
        std::future::pending::<Result<(), capnp::Error>>().await
    });
}
