//! Shell cell — remote Glia REPL over Cap'n Proto.
//!
//! Evaluates Glia s-expressions in a persistent environment with
//! capability-scoped dispatch.  Registered via VatListener; each
//! incoming connection spawns a fresh cell with its own Env.
//!
//! This is the "nREPL for Wetware": client sends text, cell evaluates,
//! result comes back.  State persists across evals (def sticks).

use std::cell::RefCell;
use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::rc::Rc;

use capnp::capability::Promise;
use capnp_rpc::pry;

use glia::eval::{self, Dispatch, Env};
use glia::Val;

use wasip2::exports::cli::run::Guest;

// Generated Cap'n Proto modules.
mod system_capnp {
    include!(concat!(env!("OUT_DIR"), "/system_capnp.rs"));
}
mod stem_capnp {
    include!(concat!(env!("OUT_DIR"), "/stem_capnp.rs"));
}
mod routing_capnp {
    include!(concat!(env!("OUT_DIR"), "/routing_capnp.rs"));
}
mod http_capnp {
    include!(concat!(env!("OUT_DIR"), "/http_capnp.rs"));
}
mod shell_capnp {
    include!(concat!(env!("OUT_DIR"), "/shell_capnp.rs"));
}

// Schema CID constants (generated by build.rs).
mod schema_ids {
    include!(concat!(env!("OUT_DIR"), "/schema_ids.rs"));
}

type Membrane = stem_capnp::membrane::Client;

// ---------------------------------------------------------------------------
// Session — capability context for the shell cell
// ---------------------------------------------------------------------------

struct ShellSession {
    host: Option<system_capnp::host::Client>,
    runtime: Option<system_capnp::runtime::Client>,
    routing: Option<routing_capnp::routing::Client>,
    http_client: Option<http_capnp::http_client::Client>,
    initialized: bool,
}

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

type HandlerFn = for<'a> fn(
    &'a [Val],
    &'a RefCell<ShellSession>,
) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>>;

struct ShellDispatch<'s> {
    ctx: &'s RefCell<ShellSession>,
    table: &'s HashMap<&'static str, HandlerFn>,
}

impl<'s> Dispatch for ShellDispatch<'s> {
    fn call<'a>(
        &'a self,
        name: &'a str,
        args: &'a [Val],
    ) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>> {
        Box::pin(async move {
            match self.table.get(name) {
                Some(handler) => handler(args, self.ctx).await,
                None => Err(Val::from(format!("{name}: command not found"))),
            }
        })
    }
}

fn build_dispatch() -> HashMap<&'static str, HandlerFn> {
    let mut t: HashMap<&'static str, HandlerFn> = HashMap::new();
    t.insert("load", |a, _| Box::pin(std::future::ready(eval_load(a))));
    t.insert("help", |_, _| {
        Box::pin(std::future::ready(Ok(Val::Str(HELP_TEXT.to_string()))))
    });
    // Shell-specific exit: returns a sentinel keyword instead of process::exit.
    // The serve loop catches this and exits cleanly.
    t.insert("exit", |_, _| {
        Box::pin(std::future::ready(Ok(Val::Keyword("exit".into()))))
    });
    t
}

const HELP_TEXT: &str = "\
Remote Glia shell. Available commands:
  (perform host :id)       — peer identity
  (perform host :addrs)    — listen addresses
  (perform host :peers)    — connected peers
  (perform routing :find \"name\") — DHT lookup
  (help)                   — this message
  (exit)                   — disconnect";

// ---------------------------------------------------------------------------
// File loading (same pattern as kernel)
// ---------------------------------------------------------------------------

thread_local! {
    static LOAD_CACHE: RefCell<HashMap<String, Vec<u8>>> = RefCell::new(HashMap::new());
}

fn eval_load(args: &[Val]) -> Result<Val, Val> {
    let path = match args.first() {
        Some(Val::Str(s)) => s.clone(),
        Some(Val::Sym(s)) => s.clone(),
        _ => return Err(Val::from("load: expected a path string")),
    };

    // Normalize: ensure leading /
    let resolved = if path.starts_with('/') {
        path.clone()
    } else {
        let root = std::env::var("WW_ROOT").unwrap_or_default();
        format!("{root}/{path}")
    };

    LOAD_CACHE.with(|cache| {
        let mut cache = cache.borrow_mut();
        if let Some(bytes) = cache.get(&resolved) {
            return Ok(Val::Bytes(bytes.clone()));
        }
        match std::fs::read(&resolved) {
            Ok(bytes) => {
                cache.insert(resolved, bytes.clone());
                Ok(Val::Bytes(bytes))
            }
            Err(e) => Err(Val::from(format!("load: {resolved}: {e}"))),
        }
    })
}

// ---------------------------------------------------------------------------
// Cap handlers — same pattern as kernel, adapted for ShellSession
// ---------------------------------------------------------------------------

fn call_resume(resume: &Val, val: Val) -> Result<Val, Val> {
    match resume {
        Val::NativeFn { func, .. } => func(&[val]),
        _ => Err(Val::from("cap handler: invalid resume function")),
    }
}

fn extract_method(data: &Val) -> Result<(String, Vec<Val>), Val> {
    let items = match data {
        Val::List(items) => items,
        _ => return Err(Val::from("cap handler: expected list data")),
    };
    let method = match items.first() {
        Some(Val::Keyword(s)) => s.clone(),
        _ => {
            return Err(Val::from(
                "cap handler: first arg must be a keyword method (e.g. :id, :run)",
            ))
        }
    };
    Ok((method, items[1..].to_vec()))
}

fn get_host(ctx: &RefCell<ShellSession>) -> Result<system_capnp::host::Client, Val> {
    ctx.borrow()
        .host
        .clone()
        .ok_or_else(|| Val::from("host: not initialized (graft not complete)"))
}

fn get_routing(ctx: &RefCell<ShellSession>) -> Result<routing_capnp::routing::Client, Val> {
    ctx.borrow()
        .routing
        .clone()
        .ok_or_else(|| Val::from("routing: not initialized (graft not complete)"))
}

fn make_host_handler(host: system_capnp::host::Client) -> Val {
    Val::AsyncNativeFn {
        name: "host-handler".into(),
        func: Rc::new(move |args: Vec<Val>| {
            let host = host.clone();
            Box::pin(async move {
                let (method, _rest) = extract_method(&args[0])?;
                let resume = &args[1];

                match method.as_str() {
                    "id" => {
                        let resp = host
                            .id_request()
                            .send()
                            .promise
                            .await
                            .map_err(|e| Val::from(e.to_string()))?;
                        let peer_id_bytes = resp
                            .get()
                            .map_err(|e| Val::from(e.to_string()))?
                            .get_peer_id()
                            .map_err(|e| Val::from(e.to_string()))?;
                        let encoded = bs58::encode(peer_id_bytes).into_string();
                        call_resume(resume, Val::Str(encoded))
                    }
                    "addrs" => {
                        let resp = host
                            .addrs_request()
                            .send()
                            .promise
                            .await
                            .map_err(|e| Val::from(e.to_string()))?;
                        let addrs = resp
                            .get()
                            .map_err(|e| Val::from(e.to_string()))?
                            .get_addrs()
                            .map_err(|e| Val::from(e.to_string()))?;
                        let items: Vec<Val> = addrs
                            .iter()
                            .filter_map(|a| {
                                a.ok().and_then(|bytes| {
                                    multiaddr::Multiaddr::try_from(bytes.to_vec())
                                        .ok()
                                        .map(|ma| Val::Str(ma.to_string()))
                                })
                            })
                            .collect();
                        call_resume(resume, Val::List(items))
                    }
                    "peers" => {
                        let resp = host
                            .peers_request()
                            .send()
                            .promise
                            .await
                            .map_err(|e| Val::from(e.to_string()))?;
                        let peers = resp
                            .get()
                            .map_err(|e| Val::from(e.to_string()))?
                            .get_peers()
                            .map_err(|e| Val::from(e.to_string()))?;
                        let items: Vec<Val> = peers
                            .iter()
                            .filter_map(|p| {
                                let peer_id = p.get_peer_id().ok()?;
                                let encoded = bs58::encode(peer_id).into_string();
                                let addrs: Vec<Val> = p
                                    .get_addrs()
                                    .ok()?
                                    .iter()
                                    .filter_map(|a| {
                                        a.ok().and_then(|bytes| {
                                            multiaddr::Multiaddr::try_from(bytes.to_vec())
                                                .ok()
                                                .map(|ma| Val::Str(ma.to_string()))
                                        })
                                    })
                                    .collect();
                                Some(Val::Map(vec![
                                    (Val::Keyword("peer-id".into()), Val::Str(encoded)),
                                    (Val::Keyword("addrs".into()), Val::List(addrs)),
                                ]))
                            })
                            .collect();
                        call_resume(resume, Val::List(items))
                    }
                    other => Err(Val::from(format!("host: unknown method :{other}"))),
                }
            })
        }),
    }
}

fn make_routing_handler(routing: routing_capnp::routing::Client) -> Val {
    Val::AsyncNativeFn {
        name: "routing-handler".into(),
        func: Rc::new(move |args: Vec<Val>| {
            let routing = routing.clone();
            Box::pin(async move {
                let (method, rest) = extract_method(&args[0])?;
                let resume = &args[1];

                match method.as_str() {
                    "provide" => {
                        let key = match rest.first() {
                            Some(Val::Str(s)) => s.clone(),
                            _ => return Err(Val::from("routing :provide — expected key string")),
                        };
                        let mut req = routing.provide_request();
                        req.get().set_key(&key);
                        req.send()
                            .promise
                            .await
                            .map_err(|e| Val::from(e.to_string()))?;
                        call_resume(resume, Val::Nil)
                    }
                    "hash" => {
                        let data = match rest.first() {
                            Some(Val::Str(s)) => s.as_bytes().to_vec(),
                            Some(Val::Bytes(b)) => b.clone(),
                            _ => return Err(Val::from("routing :hash — expected string or bytes")),
                        };
                        let mut req = routing.hash_request();
                        req.get().set_data(&data);
                        let resp = req
                            .send()
                            .promise
                            .await
                            .map_err(|e| Val::from(e.to_string()))?;
                        let key = resp
                            .get()
                            .map_err(|e| Val::from(e.to_string()))?
                            .get_key()
                            .map_err(|e| Val::from(e.to_string()))?
                            .to_string()
                            .map_err(|e| Val::from(format!("{e}")))?;
                        call_resume(resume, Val::Str(key))
                    }
                    // findProviders uses streaming sink — deferred to follow-up.
                    other => Err(Val::from(format!("routing: unknown method :{other}"))),
                }
            })
        }),
    }
}

fn make_ipfs_handler() -> Val {
    Val::AsyncNativeFn {
        name: "ipfs-handler".into(),
        func: Rc::new(move |args: Vec<Val>| {
            Box::pin(async move {
                let (method, rest) = extract_method(&args[0])?;
                let resume = &args[1];

                match method.as_str() {
                    "cat" => {
                        let path = match rest.first() {
                            Some(Val::Str(s)) => s.clone(),
                            _ => return Err(Val::from("ipfs :cat — expected path string")),
                        };
                        let resolved = if path.starts_with("/ipfs/") {
                            path
                        } else {
                            let root = std::env::var("WW_ROOT").unwrap_or_default();
                            format!("{root}/{path}")
                        };
                        match std::fs::read(&resolved) {
                            Ok(bytes) => call_resume(resume, Val::Bytes(bytes)),
                            Err(e) => Err(Val::from(format!("ipfs :cat {resolved}: {e}"))),
                        }
                    }
                    "ls" => {
                        let path = match rest.first() {
                            Some(Val::Str(s)) => s.clone(),
                            _ => return Err(Val::from("ipfs :ls — expected path string")),
                        };
                        let resolved = if path.starts_with("/ipfs/") {
                            path
                        } else {
                            let root = std::env::var("WW_ROOT").unwrap_or_default();
                            format!("{root}/{path}")
                        };
                        match std::fs::read_dir(&resolved) {
                            Ok(entries) => {
                                let items: Vec<Val> = entries
                                    .filter_map(|e| {
                                        let e = e.ok()?;
                                        let name = e.file_name().to_string_lossy().to_string();
                                        let size = e.metadata().ok()?.len();
                                        Some(Val::Map(vec![
                                            (Val::Keyword("name".into()), Val::Str(name)),
                                            (Val::Keyword("size".into()), Val::Int(size as i64)),
                                        ]))
                                    })
                                    .collect();
                                call_resume(resume, Val::List(items))
                            }
                            Err(e) => Err(Val::from(format!("ipfs :ls {resolved}: {e}"))),
                        }
                    }
                    other => Err(Val::from(format!("ipfs: unknown method :{other}"))),
                }
            })
        }),
    }
}

// ---------------------------------------------------------------------------
// Effect handler wrapping — nests with-effect-handler forms around an expr
// ---------------------------------------------------------------------------

fn wrap_with_handlers(form: &Val) -> Val {
    // Innermost: :load effect handler
    let with_load = Val::List(vec![
        Val::Sym("with-effect-handler".into()),
        Val::Keyword("load".into()),
        Val::List(vec![
            Val::Sym("fn".into()),
            Val::Vector(vec![Val::Sym("path".into()), Val::Sym("resume".into())]),
            Val::List(vec![
                Val::Sym("resume".into()),
                Val::List(vec![Val::Sym("load".into()), Val::Sym("path".into())]),
            ]),
        ]),
        form.clone(),
    ]);

    // Wrap in cap handlers (innermost to outermost)
    let caps = ["routing", "ipfs", "host"];
    let mut wrapped = with_load;
    for cap_name in &caps {
        let handler_name = format!("{cap_name}-handler");
        wrapped = Val::List(vec![
            Val::Sym("with-effect-handler".into()),
            Val::Sym(cap_name.to_string()),
            Val::Sym(handler_name),
            wrapped,
        ]);
    }
    wrapped
}

// ---------------------------------------------------------------------------
// Shell server — Cap'n Proto interface implementation
// ---------------------------------------------------------------------------

struct ShellImpl {
    env: Rc<RefCell<Env>>,
    ctx: Rc<RefCell<ShellSession>>,
    dispatch: HashMap<&'static str, HandlerFn>,
    ready: Rc<std::cell::Cell<bool>>,
}

#[allow(refining_impl_trait)]
impl shell_capnp::shell::Server for ShellImpl {
    fn eval(
        self: capnp::capability::Rc<Self>,
        params: shell_capnp::shell::EvalParams,
        mut results: shell_capnp::shell::EvalResults,
    ) -> Promise<(), capnp::Error> {
        let text = match pry!(params.get()).get_text() {
            Ok(t) => match t.to_str() {
                Ok(s) => s.to_string(),
                Err(_) => {
                    results.get().set_result("invalid UTF-8 input");
                    results.get().set_is_error(true);
                    return Promise::ok(());
                }
            },
            Err(e) => {
                results.get().set_result(&format!("{e}"));
                results.get().set_is_error(true);
                return Promise::ok(());
            }
        };

        Promise::from_future(async move {
            // Check that the serve closure has finished initializing.
            if !self.ready.get() {
                results
                    .get()
                    .set_result("shell not ready (initialization in progress)");
                results.get().set_is_error(true);
                return Ok(());
            }

            if text.trim().is_empty() {
                results.get().set_result("");
                results.get().set_is_error(false);
                return Ok(());
            }

            // Parse
            let expr = match glia::read(&text) {
                Ok(expr) => expr,
                Err(e) => {
                    results.get().set_result(&format!("parse error: {e}"));
                    results.get().set_is_error(true);
                    return Ok(());
                }
            };

            // Wrap in effect handlers and evaluate
            let wrapped = wrap_with_handlers(&expr);
            let dispatch = ShellDispatch {
                ctx: &*self.ctx,
                table: &self.dispatch,
            };
            match eval::eval_toplevel(&wrapped, &mut self.env.borrow_mut(), &dispatch).await {
                Ok(Val::Nil) => {
                    results.get().set_result("");
                    results.get().set_is_error(false);
                }
                Ok(Val::Keyword(ref k)) if k == "exit" => {
                    results.get().set_result("exit");
                    results.get().set_is_error(false);
                }
                Ok(result) => {
                    results.get().set_result(&format!("{result}"));
                    results.get().set_is_error(false);
                }
                Err(e) => {
                    results.get().set_result(&format!("{e}"));
                    results.get().set_is_error(true);
                }
            }
            Ok(())
        })
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

struct Shell;

impl Guest for Shell {
    fn run() -> Result<(), ()> {
        run_impl();
        Ok(())
    }
}

wasip2::cli::command::export!(Shell);

fn run_impl() {
    let env = Rc::new(RefCell::new(Env::new()));
    let ctx = Rc::new(RefCell::new(ShellSession {
        host: None,
        runtime: None,
        routing: None,
        http_client: None,
        initialized: false,
    }));
    let dispatch = build_dispatch();
    let ready = Rc::new(std::cell::Cell::new(false));

    let shell_impl = ShellImpl {
        env: Rc::clone(&env),
        ctx: Rc::clone(&ctx),
        dispatch: build_dispatch(),
        ready: Rc::clone(&ready),
    };
    let client: shell_capnp::shell::Client = capnp_rpc::new_client(shell_impl);

    system::serve(client.client, |_membrane: Membrane| async move {
        // Load the prelude synchronously (macro definitions only, no capability calls).
        {
            let mut env = env.borrow_mut();
            let prelude_forms = glia::read_many(glia::PRELUDE).expect("prelude: parse error");
            struct NoopDispatch;
            impl Dispatch for NoopDispatch {
                fn call<'a>(
                    &'a self,
                    name: &'a str,
                    _args: &'a [Val],
                ) -> Pin<Box<dyn Future<Output = Result<Val, Val>> + 'a>> {
                    Box::pin(std::future::ready(Err(Val::from(format!(
                        "{name}: not available"
                    )))))
                }
            }
            let mut noop = NoopDispatch;
            for form in &prelude_forms {
                // Prelude macros (defmacro) don't make async calls — single poll suffices.
                let mut fut = Box::pin(eval::eval_toplevel(form, &mut env, &noop));
                let waker = std::task::Waker::noop();
                let mut cx = std::task::Context::from_waker(&waker);
                match fut.as_mut().poll(&mut cx) {
                    std::task::Poll::Ready(Ok(_)) => {}
                    std::task::Poll::Ready(Err(e)) => log::error!("prelude: {e}"),
                    std::task::Poll::Pending => log::error!("prelude: unexpected pending"),
                }
            }
        }

        ready.set(true);

        // Keep alive. The RPC system drives eval calls concurrently.
        std::future::pending::<Result<(), capnp::Error>>().await
    });
}
