// This file includes the generated Cap'n Proto types
// Generated by build.rs from src/auth.capnp
// TODO: Re-enable when capnpc build script is fixed

// pub mod auth_capnp {
//     include!(concat!(env!("OUT_DIR"), "/auth_capnp.rs"));
// }

// pub use auth_capnp::*;
