// This file includes the generated Cap'n Proto types
// Generated by build.rs from src/swarm.capnp

pub mod swarm_capnp {
    include!(concat!(env!("OUT_DIR"), "/swarm_capnp.rs"));
}

pub use swarm_capnp::*;
