// This file includes the generated Cap'n Proto types
// Generated by build.rs from src/swarm.capnp

#[allow(dead_code)]
pub mod generated {
    include!(concat!(env!("OUT_DIR"), "/swarm_capnp.rs"));
}

pub use generated::*;
